% File description
% Name : quadcopter_init				
% Author : Luke Heyerdahl - ANL		                          				
% Description : Initialize the parameters used in the quadcopter

% Proprietary : public
% Protected: false

% Models :  tc_plant_map_trqloss_funTW -- (parent)

% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Mar-2021 16:39:36
%  MATLAB version: 9.6.0.1150989 (R2019a) Update 4
% -------------------------------------------------------------------

powerplant.tc.plant.init.ratio = 1; % Gear ratio for motor to propeller
powerplant.tc.plant.init.inertia = 0;
powerplant.tc.plant.init.mass.total = 10;
powerplant.tc.plant.init.spd_thresh = 10;
powerplant.tc.plant.init.eff_max = 1;


