% File description
% Name : quadcopter_init				
% Author : Luke Heyerdahl - ANL		                          				
% Description : Initialize the parameters used in the quadcopter

% Proprietary : public
% Protected: false

% Models :  tc_plant_map_trqloss_funTW -- (parent)

% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Mar-2021 16:39:36
%  MATLAB version: 9.6.0.1150989 (R2019a) Update 4
% -------------------------------------------------------------------

tc.plant.init.ratio         = powerplant.tc.plant.init.ratio;
tc.plant.init.inertia       = powerplant.tc.plant.init.inertia;
tc.plant.init.mass.total    = powerplant.tc.plant.init.mass.total;
tc.plant.init.spd_thresh    = powerplant.tc.plant.init.spd_thresh;
tc.plant.init.eff_max       = powerplant.tc.plant.init.eff_max;

tc.plant.init.eff_trq.idx1_trq = [0 5000];
tc.plant.init.eff_trq.idx2_spd = [0 1500];
tc.plant.init.eff_trq.map = ...
   [1 1;
    1 1];

tc.plant.init.trq_loss.idx1_trq = [0 5000];
tc.plant.init.trq_loss.idx2_spd = [0 1500];
tc.plant.init.trq_loss.map = ...
   [0   0;
    0   0];


